services:
  luacheck:
    image: ragedunicorn/luacheck:1.2.0-alpine3.24.1-1
    container_name: pulse-luacheck
    volumes:
      - ./:/workspace:ro
    working_dir: /workspace
    command: ["."]
  luacheck-report:
    image: ragedunicorn/luacheck:1.2.0-alpine3.24.1-1
    container_name: pulse-luacheck-report
    volumes:
      - ./:/workspace:ro
      - ./target:/reports
    working_dir: /workspace
    entrypoint: /bin/sh
    command: ["-c", "luacheck --formatter JUnit . > /reports/luacheck-junit.xml"]
  busted:
    image: ragedunicorn/busted:2.3.0-alpine3.24.1-1
    container_name: pulse-busted
    volumes:
      - ./:/workspace
    working_dir: /workspace
